anode:
  x_lower_bound:
    value: -1000
    unit: cm
  x_upper_bound:
    value: 1000
    unit: cm
  y_lower_bound:
    value: -1000
    unit: cm
  y_upper_bound:
    value: 1000
    unit: cm
  z_lower_bound:
    value: 0
    unit: cm
  z_upper_bound:
    value: 1000
    unit: cm
    
coarse_tiles:
  type: coarse_tiles
  pitch:
    value: 5
    unit: cm
  gap:
    value: 0.01
    unit: cm
  power_per_tile:
    value: 1.e-3
    unit: J/s
  noise:
    value: 50
    unit: e
  threshold_sigma: 5.0
  signal_fraction: 1
  clock_interval:
    value: 1.
    unit: us
  z_bin_width: 50
  integration_length: 1

pixels:
  type: pixels
  pitch:
    value: 1
    unit: cm
  power_per_pixel:
    value: 1.e-3
    unit: J/s
  noise:
    value: 50
    unit: e
  threshold_sigma: 4.0
  clock_interval:
    value: 1.
    unit: us
  z_bin_width: 10
  integration_length: 1
